### ISSUE TITLE
Proposal: Feedback

### ISSUE THREAD

**Issue by s-pangburn** [kchansf5/etsy_clone#1]
Hey Ken! This proposal doesn't look complete. Try to get it done before tomorrow or you won't be able to begin on your fullstack until I sign off on it! Please use [the BlueBird wiki](https://github.com/appacademy/bluebird/wiki) as a reference and copy it to the tee (this has been updated since the version in the homeworks, so be sure to look it over again even if you're familiar with it!

Here is a general checklist of things to look out for:

### Wiki Page Home

- [ ] Is the first page you see upon entering the wiki
- [ ] Contains a welcome message
- [ ] Contains a link/placeholder for a link to the live page
- [ ] All links in the right sidebar should contain each wiki page and link to the correct page
- [ ] Correctly formatted
    - [ ] each wiki page is listed in bullet points
    - [ ] all links route the correct page

### MVP List

- [ ] Should have 7 MVPs.
    - [ ] 3 of those are User Auth, Heroku, and Production README.
    - [ ] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [ ] Contains a description sentence of the app
- [ ] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [ ] Estimates how long it will take the code each MVP
- [ ] Each App specific MVP needs the following bullet points are added:
    + Adequate styling
    + Smooth, bug-free navigation
    + Seeded with info to demonstrate this feature

- [ ] Correctly formatted
    - [ ] MVPs are listed in an ordered list
    - [ ] Each MVP is broken down into bullet points

### Database Schema
- [ ] Contains correct datatypes
- [ ] Contains appropriate constraints/details
    - [ ] primary key
    - [ ] not null
    - [ ] unique
    - [ ] indexed
    - [ ] foreign key
- [ ] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made

- [ ] Correctly formatted
    - [ ] schema is written in a table format
    - [ ] the table's name are `back_ticked`
    - [ ] the table header column names are bolded
    - [ ] columns names are lowercased and snaked_cased and `back_ticked`

### Routes

- [ ] Routes accurately reflect MVPs and Component Hierarchy
- [ ] Covers the frontend functionality of the site through routes that match to the wireframes
- [ ] Contains the following sections: HTML, API Endpoints(Backend), and Frontend Routes
- [ ] Each route has a description
- [ ] API Endpoint routes contains wildcard variables written in `snake_case`
- [ ] Frontend routes contains wildcard variables written in `camelCase`
- [ ] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [ ] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint bc that info comes through the post show
- [ ] Correctly formatted
    - [ ] Routes are displayed with `inline coding text` (backticks)

### Sample State
- [ ] State shape is flat!
- [ ] State's keys are camelCased
- [ ] All keys within the values in the state are accessible in the schema (Ex: if you create a `imgUrl` key in the state, make sure your database also has a column that contains an `img_url`)
- [ ] Correctly formatted
    - [ ] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [ ] Top level slices
        - [ ] `entities`
        - [ ] `session`
        - [ ] `errors` (here or in `ui`)
        - [ ] `ui` (if needed)
    - [ ] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

### Component Hierarchy with Wireframes

- [ ] All routes listed in the routes wiki page is also listed in the component hierarchy
- [ ] Each component, if necessary, has route, state, and other components it renders [example](https://github.com/appacademy/bluebird/wiki/component-hierarchy)
- [ ] Necessary components are wrapped in a container
- [ ] Correctly formatted
    - [ ] Bullet point hierarchy
    - [ ] Component names are displayed with `inline coding text` (backticks)
- [ ] Wireframes included
  - [ ] Every component listed in the component hierarchy wiki page has at least one wireframe
  - [ ] Every MVPs listed on the MVP wiki page has at least one wireframe
  - [ ] Every route listed on the route wiki page has at least one wireframe
  - [ ] Contains Containers
  - [ ] Contains multiple Index/List
  - [ ] Contains multiple IndexItems/ListItems
  - [ ] Correctly formatted
    - [ ] Wireframe images display on the page
    - [ ] Every wireframe has a header title

**Comment by kchansf5** [comment]
Hey Stephen,

Thanks for the feedback. This checklist helps a lot. I will work on updating my proposal tonight!

**Comment by kchansf5** [comment]
Hey Stephen,

I've made updates to my proposal according to the checklist. Do I need to close this issue, or leave it open until the proposal is approved?

**Comment by s-pangburn** [comment]
It would be better if I close it once I've had a chance to review! That being said, this looks great! Awesome job, especially on those wireframes! Well done 👌

**Comment by kchansf5** [comment]
Sounds good. Thanks Stephen.
