### ISSUE TITLE
PA Review - New account creation, login, and guest/demo login

### ISSUE THREAD

**Issue by kchansf5** [kchansf5/etsy_clone#3]
- Users can sign up, sign in, logout
- Users can use a demo login to test the site
- Users can't user certain features without logging in (leave comments/reviews and access shopping cart)

**Comment by s-pangburn** [comment]
Wow, Ken! This looks great and the functionality is really polished! Awesome work! I really only have minimal feedback for you this time 🙌 

- [ ] When I open the Chrome console, the cart icon gets pushed off the page
- [ ] Pressing enter to submit either login or signup doesn't work. It just switches the form type?
- [ ] My name or some other indication that this is my account should be in the nav bar!
- [ ] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page (ask your circle mates if you're confused how to do this, I had them all do it already :)

**Comment by kchansf5** [comment]
Hey Stephen,

I have finished making the changes mentioned above. Please take a look and let me know if everything looks good for signing off. Thanks!

**Comment by s-pangburn** [comment]
🎉
