### ISSUE TITLE
PA Review - Product Listings 

### ISSUE THREAD

**Issue by kchansf5** [kchansf5/etsy_clone#4]
Hey Stephen, 

I've completed the product index page and individual show pages.

- Users can browse the website and view featured products from the homepage
- Users can view a list of products under a specific category <-- _this is currently incomplete (will get to categories at a later time like we talked about yesterday)_
- Users can view a single product's show page

**Comment by s-pangburn** [comment]
- [x] Your links should be relative (preferably using React Router `<Link>` tags. All of your links currently go to `localhost:3000` instead of heroku!!
- [x] Also did you make sure to seed your live database on heroku? I don't see any products 🤔

**Comment by kchansf5** [comment]
Hey Stephen,

Links should be relative now, and database is seeded.

Please take a look and sign off if everything looks okay. Thanks!

**Comment by s-pangburn** [comment]
Great job Ken! Just some small styling things:

- [x] On the product show page, your product names should have a font size closer to `40px`. Considering how little there is on the page right now, it helps balance things out a little better.
- [x] It would be nice if you could style the quantity dropdown to look more like the rest of your website. If you're finding this too much of a pain though, feel free to move on to either Shopping Cart or Reviews :)

**Comment by kchansf5** [comment]
Hey Stephen,

Both of the changes have been made. Please double check, thanks!

**Comment by s-pangburn** [comment]
Looks good! No feedback 👍
